// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to optimize website content based on traffic and engagement data.
 *
 * - optimizeWebsiteContent - A function that handles the content optimization process.
 * - OptimizeWebsiteContentInput - The input type for the optimizeWebsiteContent function.
 * - OptimizeWebsiteContentOutput - The return type for the optimizeWebsiteContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OptimizeWebsiteContentInputSchema = z.object({
  pageName: z.string().describe('The name of the page to optimize (e.g., home, about, products).'),
  currentTitle: z.string().describe('The current title of the page.'),
  currentDescription: z.string().describe('The current description of the page.'),
  trafficData: z.string().describe('JSON string of traffic data for the page (e.g., page views, bounce rate).'),
  engagementData: z.string().describe('JSON string of user engagement data (e.g., time on page, scroll depth).'),
});
export type OptimizeWebsiteContentInput = z.infer<typeof OptimizeWebsiteContentInputSchema>;

const OptimizeWebsiteContentOutputSchema = z.object({
  optimizedTitle: z.string().describe('The AI-suggested optimized title for the page.'),
  optimizedDescription: z.string().describe('The AI-suggested optimized description for the page.'),
  optimizationRationale: z.string().describe('Explanation of why the AI suggested these changes.'),
});
export type OptimizeWebsiteContentOutput = z.infer<typeof OptimizeWebsiteContentOutputSchema>;

export async function optimizeWebsiteContent(input: OptimizeWebsiteContentInput): Promise<OptimizeWebsiteContentOutput> {
  return optimizeWebsiteContentFlow(input);
}

const optimizeWebsiteContentPrompt = ai.definePrompt({
  name: 'optimizeWebsiteContentPrompt',
  input: {schema: OptimizeWebsiteContentInputSchema},
  output: {schema: OptimizeWebsiteContentOutputSchema},
  prompt: `You are an AI assistant specialized in website content optimization for SEO and user engagement.

You will receive the current title and description of a page, along with traffic and engagement data.
Based on this information, you will suggest an optimized title and description, and explain your reasoning.

Page Name: {{{pageName}}}
Current Title: {{{currentTitle}}}
Current Description: {{{currentDescription}}}
Traffic Data: {{{trafficData}}}
Engagement Data: {{{engagementData}}}

Optimize the title and description to improve SEO and user engagement. Consider factors such as keyword relevance, click-through rate, and time on page.
Provide a clear rationale for your suggestions.
`,
});

const optimizeWebsiteContentFlow = ai.defineFlow(
  {
    name: 'optimizeWebsiteContentFlow',
    inputSchema: OptimizeWebsiteContentInputSchema,
    outputSchema: OptimizeWebsiteContentOutputSchema,
  },
  async input => {
    const {output} = await optimizeWebsiteContentPrompt(input);
    return output!;
  }
);
