// This is an autogenerated file from Firebase Studio.
"use server";

import { z } from "zod";
import { addMessage } from "@/lib/messagesStore";

const formSchema = z.object({
  name: z.string().min(2, { message: "O nome deve ter pelo menos 2 caracteres." }),
  email: z.string().email({ message: "Por favor, insira um email válido." }),
  subject: z.string().min(5, { message: "O assunto deve ter pelo menos 5 caracteres." }),
  message: z.string().min(10, { message: "A mensagem deve ter pelo menos 10 caracteres." }),
});

export async function handleContactSubmit(values: z.infer<typeof formSchema>) {
  const parsed = formSchema.safeParse(values);

  if (!parsed.success) {
    return { success: false, error: "Dados inválidos." };
  }

  try {
    // Para o protótipo, adicionamos a uma "store" em memória.
    // Em um aplicativo real, isso seria salvo em um banco de dados.
    addMessage(parsed.data);

    // Simula atraso de rede
    await new Promise(resolve => setTimeout(resolve, 1000));

    return { success: true };
  } catch (error) {
    console.error("Erro ao processar formulário de contato:", error);
    return { success: false, error: "Ocorreu um erro no servidor." };
  }
}
