// This is an autogenerated file from Firebase Studio.
"use client";

import { useState } from "react";
import { Shield, Settings, ShoppingBag, Home, Award, Mail, MessageSquare, Share2 } from "lucide-react";
import AdminLogin from "./AdminLogin";
import ProductManager from "./ProductManager";
import AboutManager from "./AboutManager";
import HomeManager from "./HomeManager";
import QualityManager from "./QualityManager";
import ContactManager from "./ContactManager";
import MessagesManager from "./MessagesManager";
import FooterManager from "./FooterManager";
import { Button } from "@/components/ui/button";

type ActiveManager = 'products' | 'sobre' | 'home' | 'quality' | 'contact' | 'messages' | 'footer';

export default function AdminPage() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [activeManager, setActiveManager] = useState<ActiveManager | null>(null);

  const handleLoginSuccess = () => {
    setIsAuthenticated(true);
  };

  if (!isAuthenticated) {
    return <AdminLogin onLoginSuccess={handleLoginSuccess} />;
  }

  return (
    <div className="min-h-screen bg-muted">
      <div className="container mx-auto px-4 py-12">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
            <div className="flex items-center gap-4">
                <Shield className="h-10 w-10 text-primary" />
                <div>
                    <h1 className="text-4xl font-semibold">Painel de Administração</h1>
                    <p className="text-muted-foreground">Gerencie o conteúdo e as mensagens do seu site.</p>
                </div>
            </div>
            <div className="flex flex-wrap gap-2">
                <Button onClick={() => setActiveManager('home')} variant={activeManager === 'home' ? 'default' : 'outline'}>
                    <Home className="mr-2 h-4 w-4" />
                    Gerenciar Início
                </Button>
                <Button onClick={() => setActiveManager('sobre')} variant={activeManager === 'sobre' ? 'default' : 'outline'}>
                    <Settings className="mr-2 h-4 w-4" />
                    Gerenciar Sobre Nós
                </Button>
                <Button onClick={() => setActiveManager('products')} variant={activeManager === 'products' ? 'default' : 'outline'}>
                    <ShoppingBag className="mr-2 h-4 w-4" />
                    Gerenciar Produtos
                </Button>
                <Button onClick={() => setActiveManager('quality')} variant={activeManager === 'quality' ? 'default' : 'outline'}>
                    <Award className="mr-2 h-4 w-4" />
                    Gerenciar Qualidade
                </Button>
                <Button onClick={() => setActiveManager('contact')} variant={activeManager === 'contact' ? 'default' : 'outline'}>
                    <Mail className="mr-2 h-4 w-4" />
                    Gerenciar Contato
                </Button>
                <Button onClick={() => setActiveManager('messages')} variant={activeManager === 'messages' ? 'default' : 'outline'}>
                    <MessageSquare className="mr-2 h-4 w-4" />
                    Gerenciar Mensagens
                </Button>
                <Button onClick={() => setActiveManager('footer')} variant={activeManager === 'footer' ? 'default' : 'outline'}>
                    <Share2 className="mr-2 h-4 w-4" />
                    Gerenciar Rodapé
                </Button>
            </div>
        </div>
        
        <div className="mt-8">
          {activeManager === 'home' && <HomeManager />}
          {activeManager === 'sobre' && <AboutManager />}
          {activeManager === 'products' && <ProductManager />}
          {activeManager === 'quality' && <QualityManager />}
          {activeManager === 'contact' && <ContactManager />}
          {activeManager === 'messages' && <MessagesManager />}
          {activeManager === 'footer' && <FooterManager />}
          {!activeManager && (
            <div className="text-center py-20 bg-card rounded-lg shadow-sm">
                <h2 className="text-2xl font-semibold text-muted-foreground">Selecione uma área para gerenciar.</h2>
                <p className="text-muted-foreground mt-2">Clique em um dos botões acima para começar a editar.</p>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
